# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

schedules:
- cron: "0 0 * * *"
  displayName: Monthly First Thursday Patching
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Open_Jira_Ticket
  jobs:
  - job: Open_Jira_Ticket
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Open Jira Ticket...
- stage: Patch_QA_Group
  jobs:
  - job: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PreNotification
  - job: Install_Windows_Updates
    dependsOn: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Install windows updates...
  - job: Send_PostNotification
    dependsOn: Install_Windows_Updates
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PostNotification
  - job: Update_Jira_Ticket
    dependsOn: Send_PostNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Update Jira Ticket
- stage: Patch_Test_Group
  jobs:
    - job: Send_PreNotification
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Send PreNotification
    - job: Install_Windows_Updates
      dependsOn: Send_PreNotification
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Install windows updates...
    - job: Send_PostNotification
      dependsOn: Install_Windows_Updates
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Send PostNotification
    - job: Update_Jira_Ticket
      dependsOn: Send_PostNotification
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Update Jira Ticket
- stage: Patch_Staging_Group
  jobs:
  - job: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PreNotification
  - job: Install_Windows_Updates
    dependsOn: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Install windows updates...
  - job: Send_PostNotification
    dependsOn: Install_Windows_Updates
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PostNotification
  - job: Update_Jira_Ticket
    dependsOn: Send_PostNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Update Jira Ticket
- stage: Check_Jira_Ticket_Approval
  jobs:
  - job: Check_Jira_Ticket_Approval
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo check jira ticket approval...
- stage: Patch_Prod_Group
  jobs:
  - job: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PreNotification
  - job: Install_Windows_Updates
    dependsOn: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Install windows updates...
  - job: Send_PostNotification
    dependsOn: Install_Windows_Updates
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PostNotification
  - job: Update_Jira_Ticket
    dependsOn: Send_PostNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Update Jira Ticket
- stage: Patch_Infra_Group
  jobs:
  - job: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PreNotification
  - job: Install_Windows_Updates
    dependsOn: Send_PreNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Install windows updates...
  - job: Send_PostNotification
    dependsOn: Install_Windows_Updates
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Send PostNotification
  - job: Update_Jira_Ticket
    dependsOn: Send_PostNotification
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Update Jira Ticket
- stage: Close_Jira_Ticket
  jobs:
  - job: Close_Jira_Ticket 
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo close jira ticket

# steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'