# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

schedules:
- cron: "0 0 * * *"
  displayName: Monthly First Thursday Patching
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Open_Jira_Ticket
  jobs:
  - deployment: Open_Jira_Ticket
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Open Jira Ticket...
- stage: Patch_QA_Group
  jobs:
  - deployment: Send_PreNotification
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PreNotification
  - deployment: Install_Windows_Updates
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Install windows updates...
  - deployment: Send_PostNotification
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PostNotification
  - deployment: Update_Jira_Ticket
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Update Jira Ticket
- stage: Patch_Test_Group
  jobs:
    - deployment: Send_PreNotification
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CmdLine@2
              inputs:
                script: |
                  echo Send PreNotification
    - deployment: Install_Windows_Updates
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CmdLine@2
              inputs:
                script: |
                  echo Install windows updates...
    - deployment: Send_PostNotification
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CmdLine@2
              inputs:
                script: |
                  echo Send PostNotification
    - deployment: Update_Jira_Ticket
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CmdLine@2
              inputs:
                script: |
                  echo Update Jira Ticket
- stage: Patch_Staging_Group
  jobs:
  - deployment: Send_PreNotification
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PreNotification
  - deployment: Install_Windows_Updates
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Install windows updates...
  - deployment: Send_PostNotification
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PostNotification
  - deployment: Update_Jira_Ticket
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Update Jira Ticket
- stage: Check_Jira_Ticket_Approval
  jobs:
  - deployment: Check_Jira_Ticket_Approval
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo check jira ticket approval...
- stage: Patch_Prod_Group
  jobs:
  - deployment: Send_PreNotification
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PreNotification
  - deployment: Install_Windows_Updates
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Install windows updates...
  - deployment: Send_PostNotification
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PostNotification
  - deployment: Update_Jira_Ticket
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Update Jira Ticket
- stage: Patch_Infra_Group
  jobs:
  - deployment: Send_PreNotification
    environment: infra
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PreNotification
  - deployment: Install_Windows_Updates
    environment: infra
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Install windows updates...
  - deployment: Send_PostNotification
    environment: infra
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Send PostNotification
  - deployment: Update_Jira_Ticket
    environment: infra
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Update Jira Ticket
- stage: Close_Jira_Ticket
  jobs:
  - deployment: Close_Jira_Ticket 
    environment: infra
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo close jira ticket

# steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'