# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

schedules:
- cron: "0 0 * * *"
  displayName: Monthly First Thursday Patching
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Open Jira Ticket
  jobs:
  - job: Open Jira Ticket
    steps:
    - task: Open_Jria_Ticket@1
      inputs:
        script: |
          echo Open Jira Ticket...
- stage: Patch QA Group
  jobs:
  - job: Send Pre-Notification
    steps:
    - task: Send_Pre-Notification@1
      inputs:
        script: |
          echo Send Pre-Notification

# steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'